name: Continue building macOS binaries of Helium

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build_job:
    name: Resuming Building Helium for macOS
    runs-on: ${{ inputs.os }}
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/prepare-environment
      - name: Get previous logs
        uses: actions/download-artifact@v4
        with:
          name: github_build_logs_${{ inputs.arch }}
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: github_build_artifact_${{ inputs.arch }}
      - name: Unpack archive of build
        run: ./github_unpack_archive.sh
      - uses: ./.github/actions/do-build
        with:
          arch: ${{ inputs.arch }}
          os: ${{ inputs.os }}
          MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}

